- name: Get platform monitor docker name
  shell: docker ps -a --format '{{'{{'}}.Image{{'}} {{'}}.Names{{'}}'}}' | grep 'platform' | awk '{print $2}'
  register: pmon_ps

- name: Get platform name
  shell: show platform summary | grep Platform | awk '{print $2}'
  register: platform

- name: Gather sensors
  sensors_facts: checks={{ sensors_checks[platform.stdout] }}
  vars:
    ansible_shell_type: docker
    container_name: "{{ pmon_ps.stdout }}"

- name: Output of sensors information
  debug: var=vars['sensors']

- name: Assert no alarm
  assert: { that: "{{ vars['sensors']['alarm'] }} == False" }

- name: Show warnings
  debug: var=vars['sensors']['warnings']
  when: vars['sensors']['warning']
