- name: Start the teamd docker container
  include_tasks: sonicdocker.yml
  vars:
    docker_container: teamd
    docker_image: "{{ image_id_teamd }}"
    docker_privileged: yes
    docker_state: reloaded
    docker_volumes:
    - /etc/sonic/:/etc/sonic/:ro
    docker_volumes_from:
    - database

- include_tasks: add_container_to_inventory.yml
  vars:
    container_name: teamd

- include_tasks: teamd_interface.yml
  with_items: "{{ minigraph_portchannel_interfaces }}"
  delegate_to: teamd
